
 # it is showing unboundlocalerror  local veriable 'num'referencde before assognment



def func():
    num = (1) + 3
    print(num)

func()
print(1)


